version: "2.3"

services:
  server:
    build:
      context: .
      dockerfile: examples/docker/Dockerfile
    env_file:
      - .env
    restart: on-failure
    entrypoint:
      - /root/entrypoint.sh
    ports:
      - $PORT:8000
    volumes:
      - ./src:/root/src/
